In [1]:
import sys
import scipy
import numpy
import matplotlib
import pandas
import sklearn

print('Python: {}'.format(sys.version))
print('scipy: {}'.format(scipy.__version__))
print('numpy: {}'.format(numpy.__version__))
print('matplotlib: {}'.format(matplotlib.__version__))
print('pandas: {}'.format(pandas.__version__))
print('sklearn: {}'.format(sklearn.__version__))

Python: 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
scipy: 1.6.2
numpy: 1.20.1
matplotlib: 3.3.4
pandas: 1.2.4
sklearn: 0.24.1


In [2]:
import pandas
from pandas . plotting import scatter_matrix
import matplotlib . pyplot as plt
from sklearn import model_selection
from sklearn . neighbors import KNeighborsClassifier

In [3]:
names = ['sepel - length ', 'sepal - width ', 'petal - length', 'petal - width', 'class']
ds = pandas.read_csv('iris.data.txt', names = names)
ds

sepel - length   sepal - width   petal - length  petal - width  \
0                5.1             3.5             1.4            0.2   
1                4.9             3.0             1.4            0.2   
2                4.7             3.2             1.3            0.2   
3                4.6             3.1             1.5            0.2   
4                5.0             3.6             1.4            0.2   
..               ...             ...             ...            ...   
145              6.7             3.0             5.2            2.3   
146              6.3             2.5             5.0            1.9   
147              6.5             3.0             5.2            2.0   
148              6.2             3.4             5.4            2.3   
149              5.9             3.0             5.1            1.8   

              class  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 5 columns]

In [4]:
print (ds.shape)
print (ds.head(20))
print (ds.describe())
print (ds.groupby('class').size())

(150, 5)
    sepel - length   sepal - width   petal - length  petal - width  \
0               5.1             3.5             1.4            0.2   
1               4.9             3.0             1.4            0.2   
2               4.7             3.2             1.3            0.2   
3               4.6             3.1             1.5            0.2   
4               5.0             3.6             1.4            0.2   
5               5.4             3.9             1.7            0.4   
6               4.6             3.4             1.4            0.3   
7               5.0             3.4             1.5            0.2   
8               4.4             2.9             1.4            0.2   
9               4.9             3.1             1.5            0.1   
10              5.4             3.7             1.5            0.2   
11              4.8             3.4             1.6            0.2   
12              4.8             3.0             1.4            0.1   
13         

Answer: it print the info of the ds

In [5]:
ds.plot( kind = 'box', subplots = True, layout = (2 ,2), sharex = False, sharey = False)
plt.show()

# Milestone 1

In [6]:
array = ds.values
X = array [: ,0:4]
Y = array [: ,4]

In [7]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3.0, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5.0, 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5.0, 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3.0, 1.4, 0.1],
       [4.3, 3.0, 1.1, 0.1],
       [5.8, 4.0, 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1.0, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5.0, 3.0, 1.6, 0.2],
       [5.0, 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
Y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [9]:
test_size = 0.20
seed = 7
X_train , X_test , Y_train , Y_test = model_selection.train_test_split(X, Y,test_size = test_size , random_state = seed )

In [11]:
X_train , X_test , Y_train , Y_test

(array([[6.2, 2.8, 4.8, 1.8],
        [5.7, 2.6, 3.5, 1.0],
        [4.6, 3.6, 1.0, 0.2],
        [6.9, 3.1, 5.4, 2.1],
        [6.4, 2.9, 4.3, 1.3],
        [4.8, 3.0, 1.4, 0.3],
        [5.5, 3.5, 1.3, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [7.1, 3.0, 5.9, 2.1],
        [6.7, 3.3, 5.7, 2.1],
        [6.8, 2.8, 4.8, 1.4],
        [6.4, 2.8, 5.6, 2.2],
        [6.5, 3.0, 5.5, 1.8],
        [5.7, 3.0, 4.2, 1.2],
        [5.0, 3.3, 1.4, 0.2],
        [6.7, 3.1, 4.4, 1.4],
        [6.0, 2.2, 4.0, 1.0],
        [6.4, 2.7, 5.3, 1.9],
        [4.7, 3.2, 1.6, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [7.7, 3.8, 6.7, 2.2],
        [4.3, 3.0, 1.1, 0.1],
        [6.3, 3.3, 6.0, 2.5],
        [5.5, 2.4, 3.7, 1.0],
        [5.0, 2.0, 3.5, 1.0],
        [6.5, 2.8, 4.6, 1.5],
        [5.0, 3.4, 1.6, 0.4],
        [4.4, 2.9, 1.4, 0.2],
        [5.0, 3.5, 1.6, 0.6],
        [6.7, 3.1, 4.7, 1.5],
        [7.3, 2.9, 6.3, 1.8],
        [5

Answer: it spilt data into two subsets

In [12]:
test_size = 0.40
seed = 2
X_train , X_test , Y_train , Y_test = model_selection.train_test_split(X, Y,test_size = test_size , random_state = seed )

In [13]:
X_train , X_test , Y_train , Y_test

(array([[4.8, 3.1, 1.6, 0.2],
        [5.8, 2.7, 5.1, 1.9],
        [5.7, 2.8, 4.1, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [7.7, 3.0, 6.1, 2.3],
        [6.3, 2.7, 4.9, 1.8],
        [6.1, 2.8, 4.0, 1.3],
        [5.1, 3.7, 1.5, 0.4],
        [5.7, 2.8, 4.5, 1.3],
        [5.4, 3.9, 1.3, 0.4],
        [5.8, 2.8, 5.1, 2.4],
        [5.8, 2.6, 4.0, 1.2],
        [5.1, 2.5, 3.0, 1.1],
        [5.7, 3.8, 1.7, 0.3],
        [5.5, 2.4, 3.7, 1.0],
        [5.9, 3.0, 4.2, 1.5],
        [6.7, 3.1, 4.7, 1.5],
        [7.7, 2.8, 6.7, 2.0],
        [4.9, 3.0, 1.4, 0.2],
        [6.3, 3.3, 4.7, 1.6],
        [5.1, 3.8, 1.5, 0.3],
        [5.8, 2.7, 3.9, 1.2],
        [6.9, 3.2, 5.7, 2.3],
        [4.9, 3.1, 1.5, 0.1],
        [5.0, 2.0, 3.5, 1.0],
        [4.9, 3.1, 1.5, 0.1],
        [5.0, 3.5, 1.3, 0.3],
        [5.4, 3.7, 1.5, 0.2],
        [6.8, 3.0, 5.5, 2.1],
        [6.3, 3.3, 6.0, 2.5],
        [5.0, 3.4, 1.6, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [6.3, 2.5, 5.0, 1.9],
        [7

Exercise 9

Answer: k=3 it should be Odd because if it be even it have possibility to cannot compare the better.

In [15]:
irisML = KNeighborsClassifier(n_neighbors =7)
irisML.fit( X_train , Y_train )

KNeighborsClassifier(n_neighbors=7)

In [17]:
prediction = irisML . predict ( X_test )
prediction

array(['Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
      

In [18]:
irisML.score( X_test , Y_test )

0.9666666666666667

.score() is a accuracy prediction score

In [24]:
new_obj1 = [[5.1,3.5,1.4,0.2]]
output1 = irisML . predict ( new_obj1 )
output1

array(['Iris-setosa'], dtype=object)