In [1]:
import scipy
from scipy . cluster .vq import kmeans ,vq , whiten
# Score of 20 students in on subjects
student_scores = [[80] , [78] , [55] , [60] , [62] ,
[59] , [48] , [49] , [51] , [54] ,
[72] , [95] , [78] , [54] , [50] ,
[61] , [57] , [56] , [65] , [53]];
student_scores = whiten (student_scores)
centroids ,_ = kmeans (student_scores ,2)
result ,_ = vq(student_scores , centroids )
result

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1])

In [2]:
import scipy
from scipy . cluster .vq import kmeans ,vq , whiten
# Score of 20 students in on subjects
student_scores = [[80] , [78] , [55] , [60] , [62] ,
[59] , [48] , [49] , [51] , [54] ,
[72] , [95] , [78] , [54] , [50] ,
[61] , [57] , [56] , [65] , [53]];
student_scores = whiten (student_scores)
centroids ,_ = kmeans (student_scores ,4)
result ,_ = vq(student_scores , centroids)
result

array([3, 3, 0, 2, 2, 2, 0, 0, 0, 0, 3, 1, 3, 0, 0, 2, 2, 0, 2, 0])

In [3]:
import scipy
from scipy . cluster .vq import kmeans ,vq , whiten
# Score of 20 students in on subjects
student_scores =[[80 , 72] , [78 , 56] , [55 , 64] , [60 , 61] , [62 , 45] ,
[59 , 71] , [48 , 85] , [49 , 45] , [51 , 55] , [54 , 62] ,
[72 , 81] , [95 , 81] , [78 , 92] , [54 , 80] , [50 , 50] ,
[61 , 65] , [57 , 62] , [56 , 55] , [65 , 63] , [53 , 72]];
student_scores = whiten (student_scores)
centroids ,_ = kmeans (student_scores ,4)
result ,_ = vq(student_scores , centroids)
result

array([3, 3, 0, 0, 2, 0, 1, 2, 2, 0, 3, 3, 3, 1, 2, 0, 0, 2, 0, 1])

In [4]:
import scipy.constants
print("The PI is %.16f"% scipy.constants.pi)
print("The speed of light is c = %.1F"%scipy.constants.c)
print("The newton ’s gravity constant is G = %.1F"%scipy.constants.g)

The PI is 3.1415926535897931
The speed of light is c = 299792458.0
The newton ’s gravity constant is G = 9.8


In [5]:
scipy.constants.find ("gram") 

['atomic mass unit-kilogram relationship',
 'electron volt-kilogram relationship',
 'hartree-kilogram relationship',
 'hertz-kilogram relationship',
 'inverse meter-kilogram relationship',
 'joule-kilogram relationship',
 'kelvin-kilogram relationship',
 'kilogram-atomic mass unit relationship',
 'kilogram-electron volt relationship',
 'kilogram-hartree relationship',
 'kilogram-hertz relationship',
 'kilogram-inverse meter relationship',
 'kilogram-joule relationship',
 'kilogram-kelvin relationship']

In [6]:
print (scipy.constants.physical_constants ["atomic mass unit-kilogram relationship"])

(1.6605390666e-27, 'kg', 5e-37)


In [7]:
x = float(input(""))
E = x* scipy.constants.c**2
E

55


4.943153483052497e+18

In [8]:
import scipy.stats as s
import numpy as np
x = np. array ([19 ,18 ,21 ,16 ,15 ,17 ,20 ,18]) ;
print (s.tmin(x),s.tmax(x),s.tmean(x),s.tvar(x));

15 21 18.0 4.0


In [9]:
print(s.describe(x));

DescribeResult(nobs=8, minmax=(15, 21), mean=18.0, variance=4.0, skewness=0.0, kurtosis=-1.0)


In [10]:
import scipy . stats as stats
import numpy as np
student_scores = [[80] , [78] , [55] , [60] , [62] ,
[59] , [48] , [49] , [51] , [54] ,
[72] , [95] , [78] , [54] , [50] ,
[61] , [57] , [56] , [65] , [53]];
print (stats.tmean(student_scores))
print (stats.tstd(student_scores))
print ((62 - stats.tmean(student_scores)) / stats.tstd(student_scores ))

61.85
[12.55838994]
[0.01194421]


In [11]:
count = 1
for x in student_scores:
    Z = (x-stats.tmean(student_scores))/stats.tstd(student_scores)
    print("Z%d ="%count,Z)
    count += 1

Z1 = [1.44524896]
Z2 = [1.28599288]
Z3 = [-0.54545209]
Z4 = [-0.14731188]
Z5 = [0.01194421]
Z6 = [-0.22693992]
Z7 = [-1.10284838]
Z8 = [-1.02322034]
Z9 = [-0.86396425]
Z10 = [-0.62508013]
Z11 = [0.80822462]
Z12 = [2.63966959]
Z13 = [1.28599288]
Z14 = [-0.62508013]
Z15 = [-0.9435923]
Z16 = [-0.06768384]
Z17 = [-0.386196]
Z18 = [-0.46582404]
Z19 = [0.25082833]
Z20 = [-0.70470817]
